title = "Deserted Island DevOps"
baseURL = "https://desertedisland.club"
disableKinds = ["taxonomy", "taxonomyTerm"]

[blackfriday]
hrefTargetBlank = true

[params]
tagline = "Deserted Island DevOps"
sub_tagline = "The Greatest Minds in DevOps... in Animal Crossing."
sub_description = "Join us April 30th for a free one-day event celebrating DevOps and Animal Crossing, streaming live on twitch.tv!"
font_awesome_version = "5.8.1"
mainSections = ["messages"]

[params.logos]
hero = "di_logo_big.png"

[[params.fonts]]
name = "Noto Sans"
sizes = [300,400,600,700]
type = "sans_serif"
