title = "Deserted Island DevOps"
baseURL = "https://desertedisland.club"
disableKinds = ["taxonomy", "taxonomyTerm"]
description = "Deserted Island DevOps is a one-day virtual event set in the world of Animal Crossing: New Horizons! Catch it live on twitch.tv/oncallmemaybe, 4/30/20 at 10 AM ET!"

[blackfriday]
hrefTargetBlank = true

[params]
tagline = "Deserted Island DevOps"
sub_tagline = "The best minds in technology, live from Animal Crossing!"
sub_description = "Free live streams of great tech talks, tutorials, and everything else you need for your DevOps journey."
font_awesome_version = "5.8.1"
mainSections = ["messages"]

[params.logos]
hero = "logos/di_logo_big.png"

[[params.fonts]]
name = "Noto Sans"
sizes = [300,400,600,700]
type = "sans_serif"
