title = "Deserted Island DevOps"
baseURL = "https://desertedisland.club"
disableKinds = ["taxonomy", "taxonomyTerm"]
description = "Deserted Island DevOps 2021 is coming 4/30/21!"

[blackfriday]
hrefTargetBlank = true

[params]
tagline = "Deserted Island DevOps"
sub_tagline = "Deserted Island DevOps 2021"
sub_description = "Coming 4/30/21, streaming live on twitch.tv!"
font_awesome_version = "5.8.1"
mainSections = ["messages"]

[params.logos]
hero = "logos/di_logo_big.png"

[[params.fonts]]
name = "Noto Sans"
sizes = [300,400,600,700]
type = "sans_serif"
