title = "Deserted Island DevOps"
baseURL = "https://desertedisland.club"
disableKinds = ["taxonomy", "taxonomyTerm"]
description = "Deserted Island DevOps 2022 is coming 9/14/22!"

[blackfriday]
hrefTargetBlank = true

[params]
tagline = "Deserted Island DevOps"
sub_tagline = "Deserted Island DevOps 2022"
sub_description = "See you next year!"
font_awesome_version = "5.8.1"
mainSections = ["messages"]
meta_desc = "The world's first (and only) DevOps conference in Animal Crossing!"

[params.logos]
hero = "logos/hero_2022.png"

[[params.fonts]]
name = "Noto Sans"
sizes = [300,400,600,700]
type = "sans_serif"
