title = "Deserted Island DevOps"
baseURL = "https://desertedisland.club"
disableKinds = ["taxonomy", "taxonomyTerm"]
description = "Deserted Island DevOps 2021 is coming 4/30/21!"

[blackfriday]
hrefTargetBlank = true

[params]
tagline = "Deserted Island DevOps"
sub_tagline = "Deserted Island DevOps 2021"
sub_description = "Watch Live 4/30/21 @ 8:30 AM PT / 11:30 AM ET / 4:30 PM BST"
font_awesome_version = "5.8.1"
mainSections = ["messages"]
meta_desc = "The world's first (and only) DevOps conference in Animal Crossing!"

[params.logos]
hero = "logos/hero_2021.png"

[[params.fonts]]
name = "Noto Sans"
sizes = [300,400,600,700]
type = "sans_serif"
